### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by ledzep2**

### CODE REVIEW

**Comment by adieu** [comment]
Can you rebase on master branch to remove duplicate commit?

**Comment by adieu** [comment]
It seems those two commits had already been merged. But there are more changes in this PR. Can you make a new PR with only the new changes? @ledzep2

**Comment by ledzep2** [comment]
I did a comparison. This one and PR#2 are exactly the same. However the commits have different hash. Wierd. I don't know what I was thinking and why github even let me create a duplicate PR.

**Comment by adieu** [comment]
The merge feature in github will create a new commit with information about the person doing the merge.

**Pull request closed without merging**
